tasks:
  - init: pip install -e .[dev]

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: false
    addBadge: true
    addLabel: false
