# pylint: disable=redefined-outer-name
from typing import List

import pytest


@pytest.fixture(scope="package")
def limited_allowed_intermediate_states() -> List[str]:
    return [  # old particle_list.yml
        "gamma",
        "W-",
        "W+",
        "e+",
        "e-",
        "mu+",
        "mu-",
        "tau+",
        "tau-",
        "nu(e)",
        "nu(e)~",
        "nu(mu)",
        "nu(mu)~",
        "nu(tau)",
        "nu(tau)~",
        "pi0",
        "pi+",
        "pi-",
        "eta",
        "rho(770)0",
        "rho(770)+",
        "rho(770)-",
        "omega(782)",
        "f(0)(980)",
        "f(0)(1500)",
        "f(2)(1270)",
        "f(2)(1950)",
        "a(0)(980)0",
        "a(0)(980)+",
        "a(0)(980)-",
        "a(2)(1320)0",
        "a(2)(1320)+",
        "a(2)(1320)-",
        "phi(1020)",
        "K-",
        "K+",
        "K0",
        "K~0",
        "D+",
        "D-",
        "D0",
        "D~0",
        "D*(2007)0",
        "D*(2007)~0",
        "D*(2010)-",
        "D*(2010)+",
        "D(1)(2420)0",
        "J/psi(1S)",
        "Y(4260)",
        "chi(c1)(1P)",
        "p",
        "p~",
        "n",
        "n~",
        "N(1650)+",
        "N(1650)-",
        "Delta(1232)++",
        "Delta(1232)+",
        "Delta(1232)0",
        "Delta(1232)-",
        "Lambda",
        "Lambda~",
        "Sigma0",
        "Sigma+",
        "Sigma-",
        "Xi0",
        "Xi-",
        "EpEm (4230 MeV)",
    ]
