# cspell:ignore mkdir noreply

name: CI-dev

on:
  push:
    branches: [master]

jobs:
  requirements:
    name: Unit tests + coverage
    if: github.event.pull_request.draft == false
    continue-on-error: true
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
      - name: Upgrade dependencies
        run: |
          git fetch origin
          [[ $(git diff origin/$GITHUB_BASE_REF --name-only --
            dev/requirements*.in
            dev/*/requirements*.txt
            setup.cfg)
          ]] &&
            bash dev/upgrade.sh
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.python-version }}
          path: dev/${{ matrix.python-version }}

  push:
    name: Make a PR for updated requirements files
    runs-on: ubuntu-18.04
    needs:
      - requirements
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "ci: upgrade developer dependencies"
          committer: GitHub <noreply@github.com>
          author:
            ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "ci: upgrade developer dependencies"
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          labels: |
            🖱️ DX
            🔨 Maintenance
          branch-suffix: timestamp
          delete-branch: true

      - name: Print PR info
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
