# cspell:ignore noreply

name: Requirements (PR)

on:
  pull_request:
    branches: [master]
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  requirements:
    name: Upgrade requirement files
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
      - name: Fetch repository
        run: git fetch origin
      - name: Abort if fork PR and dependency changes
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: |
          export DEPENCY_CHANGES=$(git diff origin/$GITHUB_BASE_REF --name-only -- reqs setup.cfg)
          [[ -n ${DEPENCY_CHANGES} ]] &&
            echo "Dependency changes:"
            echo ${DEPENCY_CHANGES}
            echo -e "\e[31;1mERROR: cannot modify package dependencies through a PR from a fork\e[0m" &&
            exit 1
      - name: Return success if no dependency changes
        run: "[[ -z ${DEPENCY_CHANGES} ]] && exit 0"
      - name: Upgrade dependencies
        run: bash reqs/upgrade.sh
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.python-version }}
          path: reqs/${{ matrix.python-version }}

  push:
    name: Push changes to requirement.txt files
    runs-on: ubuntu-18.04
    needs:
      - requirements
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: reqs
      - name: Commit and push changes
        run: |
          git remote set-url origin ${GITHUB_SERVER_URL}/${{ github.event.pull_request.head.repo.full_name }}
          git config --global user.name ${{ github.actor }}
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b ${GITHUB_HEAD_REF}
          git add reqs/*/requirements*.txt
          git commit -m "ci: upgrade developer dependencies (automatic)"
          git config pull.rebase true
          git pull origin ${GITHUB_HEAD_REF}
          git push origin HEAD:${GITHUB_HEAD_REF}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
